### ISSUE TITLE
HTML Playground sample prints React error every time it's loaded

### ISSUE THREAD

**Issue by peterflynn** [AdobeXD/plugin-samples#10]
1. Install the `ui-html-playground` sample
2. Launch XD and open a document
3. Look in the Developer Console

**Result**
A big error stack was logged:

```
Loading plugin /..../develop/ui-html-playground
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
    at Object.error (plugins/PluginLoader.js:45:34)
    at /..../develop/ui-html-playground/main.js:20858:17
    at Object../node_modules/schedule/cjs/schedule.development.js (/..../develop/ui-html-playground/main.js:21158:5)
    at __webpack_require__ (/..../develop/ui-html-playground/main.js:21:30)
    at Object../node_modules/schedule/index.js (/..../develop/ui-html-playground/main.js:21175:20)
    at __webpack_require__ (/..../develop/ui-html-playground/main.js:21:30)
    at /..../develop/ui-html-playground/main.js:463:16
    at Object../node_modules/react-dom/cjs/react-dom.development.js (/..../develop/ui-html-playground/main.js:18529:5)
    at __webpack_require__ (/..../develop/ui-html-playground/main.js:21:30)
    at Object../node_modules/react-dom/index.js (/..../develop/ui-html-playground/main.js:18574:20)
    at __webpack_require__ (/..../develop/ui-html-playground/main.js:21:30)
    at Object.<anonymous> (/..../develop/ui-html-playground/main.js:21920:16)
    at Object../src/main.jsx (/..../develop/ui-html-playground/main.js:21970:30)
    at __webpack_require__ (/..../develop/ui-html-playground/main.js:21:30)
    at /..../develop/ui-html-playground/main.js:85:18
    at /..../develop/ui-html-playground/main.js:88:10
...
```

**Expected**
Polyfill the rAF-related APIs as needed so React works correctly and doesn't spam errors to the console.  (Maybe someone could provide a standard set of these polyfills via https://github.com/AdobeXD/plugin-toolkit?)

**Comment by dkstevekwak** [comment]
https://github.com/AdobeXD/plugin-samples/commit/c2451eef6271ff6fc013a3548de295042d2ae4ae
